<?php
// backend/php/index.php
// Vanilla PHP Implementation of Mindful Breathing Visualizer

// Server-side logic for greeting
date_default_timezone_set('UTC');
$hour = date('H');
if ($hour < 12) {
    $greeting = "Good Morning";
} elseif ($hour < 18) {
    $greeting = "Good Afternoon";
} else {
    $greeting = "Good Evening";
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mindful Breathing (Vanilla PHP)</title>
    <style>
        :root {
            --primary-color: #34d399; /* Emerald */
            --secondary-color: #60a5fa; /* Blue */
            --accent-color: #fb7185; /* Rose */
            --bg-color: #f0f4f8;
            --text-color: #1e293b;
        }
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            margin: 0;
            background-color: var(--bg-color);
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
            color: var(--text-color);
        }
        h1 { margin-bottom: 0.5rem; }
        .greeting { font-size: 1.2rem; color: #64748b; margin-bottom: 2rem; }
        
        .visualizer-container {
            position: relative;
            width: 300px;
            height: 300px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        
        .visualizer {
            width: 100px;
            height: 100px;
            background-color: var(--primary-color);
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-weight: bold;
            font-size: 1.2rem;
            will-change: transform, background-color, border-radius;
            /* Transition handled by JS/CSS updates */
            transition: transform 4s ease-in-out, background-color 4s ease-in-out;
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
        }

        .controls {
            margin-top: 2rem;
            display: flex;
            gap: 1rem;
            flex-wrap: wrap;
            justify-content: center;
            max-width: 600px;
        }
        
        button, select {
            padding: 0.5rem 1rem;
            border: 1px solid #cbd5e1;
            border-radius: 0.5rem;
            background: white;
            cursor: pointer;
            font-size: 1rem;
            transition: all 0.2s;
        }
        
        button:hover:not(:disabled) {
            background-color: #e2e8f0;
        }
        
        button:disabled {
            opacity: 0.6;
            cursor: not-allowed;
            background-color: #e2e8f0;
        }

        .active {
            background-color: var(--secondary-color);
            color: white;
            border-color: var(--secondary-color);
        }
        
        .sr-only {
            position: absolute;
            width: 1px;
            height: 1px;
            padding: 0;
            margin: -1px;
            overflow: hidden;
            clip: rect(0, 0, 0, 0);
            white-space: nowrap;
            border-width: 0;
        }
    </style>
</head>
<body>

    <h1>Mindful Breathing</h1>
    <div class="greeting"><?php echo $greeting; ?>! Take a moment to breathe.</div>

    <button id="muteBtn" aria-label="Toggle Mute">🔊 Mute</button>

    <div class="visualizer-container">
        <div id="shape" class="visualizer" role="status" aria-live="polite">Ready</div>
    </div>

    <div class="controls">
        <label>
            Shape:
            <select id="shapeSelect">
                <option value="circle">Circle</option>
                <option value="square">Square</option>
                <option value="lotus">Lotus</option>
            </select>
        </label>
    </div>

    <div class="controls" id="techControls">
        <!-- Generated by JS -->
    </div>

<script>
// SECURITY: Immutable Configuration
const TECHNIQUES = Object.freeze({
    box: Object.freeze({
        name: 'Box Breathing',
        phases: Object.freeze([
            { name: 'Inhale', duration: 4000, scale: 1.5, color: '#34d399', x: 0 },
            { name: 'Hold', duration: 4000, scale: 1.5, color: '#60a5fa', x: 0 },
            { name: 'Exhale', duration: 4000, scale: 1.0, color: '#fb7185', x: 0 },
            { name: 'Hold', duration: 4000, scale: 1.0, color: '#60a5fa', x: 0 }
        ])
    }),
    diaphragmatic: Object.freeze({
        name: 'Diaphragmatic',
        phases: Object.freeze([
            { name: 'Inhale', duration: 5000, scale: 1.5, color: '#34d399', x: 0 },
            { name: 'Exhale', duration: 5000, scale: 1.0, color: '#fb7185', x: 0 }
        ])
    }),
    alternate: Object.freeze({
        name: 'Alternate Nostril',
        phases: Object.freeze([
            { name: 'Inhale Left', duration: 4000, scale: 1.0, color: '#34d399', x: -50 },
            { name: 'Hold', duration: 4000, scale: 1.0, color: '#60a5fa', x: 0 },
            { name: 'Exhale Right', duration: 4000, scale: 1.0, color: '#fb7185', x: 50 },
            { name: 'Hold', duration: 4000, scale: 1.0, color: '#60a5fa', x: 0 },
            { name: 'Inhale Right', duration: 4000, scale: 1.0, color: '#34d399', x: 50 },
            { name: 'Hold', duration: 4000, scale: 1.0, color: '#60a5fa', x: 0 },
            { name: 'Exhale Left', duration: 4000, scale: 1.0, color: '#fb7185', x: -50 },
            { name: 'Hold', duration: 4000, scale: 1.0, color: '#60a5fa', x: 0 }
        ])
    })
});

// Audio Controller
const AudioController = {
    ctx: null,
    oscillator: null,
    gainNode: null,
    isMuted: false,

    init() {
        if (!this.ctx) {
            this.ctx = new (window.AudioContext || window.webkitAudioContext)();
            this.gainNode = this.ctx.createGain();
            this.gainNode.connect(this.ctx.destination);
            this.gainNode.gain.value = 0;
        }
        if (this.ctx.state === 'suspended') {
            this.ctx.resume();
        }
    },

    toggleMute() {
        this.isMuted = !this.isMuted;
        if (this.gainNode) {
            this.gainNode.gain.value = this.isMuted ? 0 : 0.1;
        }
        return this.isMuted;
    },

    setPhase(phaseName, duration) {
        if (this.isMuted || !this.ctx) return;
        
        const now = this.ctx.currentTime;
        const rampTime = duration / 1000;
        
        // Ensure oscillator
        if (!this.oscillator) {
            this.oscillator = this.ctx.createOscillator();
            this.oscillator.type = 'sine';
            this.oscillator.frequency.value = 150;
            this.oscillator.connect(this.gainNode);
            this.oscillator.start();
        }

        this.oscillator.frequency.cancelScheduledValues(now);
        this.gainNode.gain.cancelScheduledValues(now);

        const lower = phaseName.toLowerCase();
        if (lower.includes('inhale')) {
            this.oscillator.frequency.setValueAtTime(150, now);
            this.oscillator.frequency.linearRampToValueAtTime(200, now + rampTime);
            this.gainNode.gain.setValueAtTime(0.1, now);
            this.gainNode.gain.linearRampToValueAtTime(0.2, now + rampTime);
        } else if (lower.includes('exhale')) {
            this.oscillator.frequency.setValueAtTime(200, now);
            this.oscillator.frequency.linearRampToValueAtTime(150, now + rampTime);
            this.gainNode.gain.setValueAtTime(0.2, now);
            this.gainNode.gain.linearRampToValueAtTime(0.1, now + rampTime);
        } else {
            // Hold
             this.gainNode.gain.setValueAtTime(this.gainNode.gain.value, now);
        }
    }
};

// Main Logic
let currentTechKey = 'box';
let phaseIndex = 0;
let phaseTimer = null;
const shapeEl = document.getElementById('shape');
const muteBtn = document.getElementById('muteBtn');
const techContainer = document.getElementById('techControls');
const shapeSelect = document.getElementById('shapeSelect');

function updateShape() {
    const shape = shapeSelect.value;
    if (shape === 'circle') {
        shapeEl.style.borderRadius = '50%';
    } else if (shape === 'lotus') {
        shapeEl.style.borderRadius = '40% 60% 70% 30% / 40% 50% 60% 50%';
    } else {
        shapeEl.style.borderRadius = '12px';
    }
}

function renderPhase() {
    const tech = TECHNIQUES[currentTechKey];
    const phase = tech.phases[phaseIndex];
    
    // Update Visuals
    shapeEl.innerText = phase.name;
    shapeEl.style.backgroundColor = phase.color;
    shapeEl.style.transition = `transform ${phase.duration}ms ease-in-out, background-color ${phase.duration}ms ease-in-out`;
    
    const scale = phase.scale;
    const x = phase.x || 0;
    shapeEl.style.transform = `scale(${scale}) translateX(${x}px)`;
    
    // Audio
    AudioController.init();
    AudioController.setPhase(phase.name, phase.duration);
    
    // Schedule next
    phaseTimer = setTimeout(() => {
        phaseIndex = (phaseIndex + 1) % tech.phases.length;
        renderPhase();
    }, phase.duration);
}

function setTechnique(key) {
    if (!TECHNIQUES[key]) return;
    currentTechKey = key;
    phaseIndex = 0;
    clearTimeout(phaseTimer);
    
    // Update buttons
    document.querySelectorAll('.tech-btn').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.key === key);
        btn.disabled = btn.dataset.key === key;
    });
    
    renderPhase();
}

// Init Controls
Object.keys(TECHNIQUES).forEach(key => {
    const btn = document.createElement('button');
    btn.innerText = TECHNIQUES[key].name;
    btn.dataset.key = key;
    btn.className = 'tech-btn';
    btn.onclick = () => setTechnique(key);
    techContainer.appendChild(btn);
});

shapeSelect.onchange = updateShape;

muteBtn.onclick = () => {
    const isMuted = AudioController.toggleMute();
    muteBtn.innerText = isMuted ? '🔇 Unmute' : '🔊 Mute';
    // Init context on user interaction if needed
    AudioController.init(); 
};

// Start
updateShape();
setTechnique('box');

</script>
</body>
</html>
