apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindful-breathing-visualizer
  labels:
    app: mindful-breathing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindful-breathing
  template:
    metadata:
      labels:
        app: mindful-breathing
    spec:
      containers:
        - name: frontend
          image: mindful-breathing:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '100m'
